### ISSUE TITLE
auto clean up trailing whitespace only

### ISSUE THREAD

**Issue by hallzy** [kuoe0/vim-janitor#10]
Would be nice to be able to only affect trailing whitespace automatically as apposed to that and blank lines

**Comment by kuoe0** [comment]
Hi, I'm not sure what you mean. Could you provide any example to me?

**Comment by hallzy** [comment]
I just submitted a PR #11 which resolves my question.

Basically, it adds a few more configuration variables so that you can choose to only enable clean up of trailing whitespace, or blank lines instead of needing to do both.

There is also one of these variables for if you want to only clean up changed lines, or the whole file.

I also added a generic auto-clean-up instead of just the auto clean changed lines.

**Comment by hallzy** [comment]
essentially what I was saying is, I want to be able to automatically clean the changed lines in my file, but I only want to clean the trailing whitespace, but not the blank lines.

**Comment by kuoe0** [comment]
Fixed in 84fb14825639c6589b7151f8c23c6efa6c398648.
