### ISSUE TITLE
Do not highlight on current line

### ISSUE THREAD

**Issue by Nohac** [kuoe0/vim-janitor#12]
It would be nice if highlighting with `JanitorHighlightAll` only appeard once you entered a new line.

I think this would make sense as it's really annoying to see a red highlight every time you press space or tab while typing.

Hope this is doable!
Thanks.

**Comment by kuoe0** [comment]
Thanks for your feedback! 

Due to I'm busy in this month, I'll investigate that in next month!

**Comment by kuoe0** [comment]
After investigation for this issue, I tried to implement this. But, the method would make hisearch failed. So, I tend to not implement this feature for now.
